name: Google Navigation Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # 3. Install the Latest Google Chrome
      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get install -fy
          echo "Installed Google Chrome version: $(google-chrome --version)"

      # 4. Detect Google Chrome Version and Install Matching ChromeDriver
      - name: Install Matching ChromeDriver
        run: |
          # Get the installed Google Chrome version
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
          echo "Detected Google Chrome version: $CHROME_VERSION"

          # Extract the major version (e.g., 114 from 114.0.5735.90)
          CHROME_MAJOR_VERSION=$(echo "$CHROME_VERSION" | cut -d. -f1)
          echo "Detected major version: $CHROME_MAJOR_VERSION"

          # Fetch the matching ChromeDriver version
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAJOR_VERSION")

          # Validate ChromeDriver version resolution
          if [ -z "$CHROMEDRIVER_VERSION" ]; then
            echo "Failed to fetch matching ChromeDriver version for Chrome $CHROME_MAJOR_VERSION. Exiting."
            exit 1
          fi
          echo "Matching ChromeDriver version: $CHROMEDRIVER_VERSION"

          # Download and install ChromeDriver
          wget https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      # 5. Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pytest

      # 6. Run Selenium Test
      - name: Run Selenium Test
        run: pytest tests/test_google_url.py
